
# Taliban in Afghanistan

Ein brisantes politisches Thema. Was passiert in Afghanistan nach dem Abzug der NATO-Truppen und der Machtübernahme der Taliban?

```{r}
library(tidyverse)
library(tidytext)
library(rtweet)
```


## Fetch Stream

```{r eval=FALSE, include=TRUE}
library(tidyverse)
library(rtweet)

## Stream keywords used to filter tweets
q <- "Afghanistan"
## Stream for 30 minutes
streamtime <- 30 * 60
## Filename to save json data (backup)
filename <- "data/afghanistan.json"

## Stream tweets
rt_rollingstones <- stream_tweets(q = q, timeout = streamtime, file_name = filename)

```

```{r eval=FALSE, include=TRUE}
library(jsonlite)
fromJSON("data/afghanistan.json")

```


## Fetch tweets

```{r eval=FALSE, include=TRUE}
library(tidyverse)
library(rtweet)

q <- "Afghanistan"
tweets_afghanistan_de <- search_tweets(q = q, 
                        n = 18000,
                        token = bearer_token(), 
                        include_rts = FALSE,
                        `-filter` = "replies",
                        lang = "de")

tweets_afghanistan_de
```


```{r eval=FALSE, include=TRUE}
q <- "Afghanistan"
tweets_afghanistan_en <- search_tweets(q = q, 
                        n = 18000,
                        token = bearer_token(), 
                        include_rts = FALSE,
                        `-filter` = "replies",
                        lang = "en")

tweets_afghanistan_en
```


```{r eval=FALSE, include=TRUE}
q <- "Afganistan"
tweets_afghanistan_sl <- search_tweets(q = q, 
                        n = 18000,
                        token = bearer_token(), 
                        include_rts = FALSE,
                        `-filter` = "replies",
                        lang = "sl")

tweets_afghanistan_sl
```


```{r eval=FALSE, include=TRUE}
q <- "Afghanistan"
tweets_afghanistan_sl2 <- search_tweets(q = q, 
                        n = 18000,
                        token = bearer_token(), 
                        include_rts = FALSE,
                        `-filter` = "replies",
                        lang = "sl")

tweets_afghanistan_sl2

```


## Gather tweets

```{r eval=FALSE, include=TRUE}
tweets_afghanistan <- bind_rows(tweets_afghanistan_sl, tweets_afghanistan_sl2,
                                tweets_afghanistan_de, tweets_afghanistan_en)
```

## Save tweets

```{r eval=FALSE, include=TRUE}
library(writexl)
write_xlsx(tweets_afghanistan, "data/tweets_afghanistan.xlsx")
write_rds(tweets_afghanistan, "data/tweets_afghanistan.rds")
```

## Load tweets

```{r}
tweets_afghanistan <- read_rds("data/tweets_afghanistan.rds")

```


## Who wrote about

```{r}
tweets_afghanistan %>% 
  filter(str_detect(screen_name, "spiegel"))

```


```{r}
tweets_afghanistan %>% 
  filter(str_detect(screen_name, "Tonin"))

```


```{r}
tweets_afghanistan %>% 
  filter(str_detect(screen_name, "SpletnaMladina"))

```


```{r}
tweets_afghanistan %>% 
  filter(str_detect(screen_name, "Dnevnik"))

```


```{r}
tweets_afghanistan %>% 
  filter((screen_name == "Delo"))

```


```{r}
tweets_afghanistan %>% 
  filter(str_detect(screen_name, "Demokracija"))

```

## Timeplot

```{r}
## plot time series of tweets
p1 <- ts_plot(tweets_afghanistan, "3 hours", color = "red") +
  ggplot2::theme_minimal() +
  ggplot2::theme(plot.title = ggplot2::element_text(face = "bold")) +
  ggplot2::labs(
    x = NULL, y = NULL,
    title = "Frequency of #Afghanistan Twitter statuses from past 9 days",
    subtitle = "Twitter status (tweet) counts aggregated using three-hour intervals",
    caption = "\nSource: Data collected from Twitter's REST API via rtweet"
  )

library(plotly)
ggplotly(p1)
```


```{r}
## plot time series of tweets
p2 <- ts_plot(tweets_afghanistan_de, "3 hours", 
              color = "darkgreen") +
  ggplot2::theme_minimal() +
  ggplot2::theme(plot.title = ggplot2::element_text(face = "bold")) +
  ggplot2::labs(
    x = NULL, y = NULL,
    title = "Frequency of #rollingstones Twitter statuses from past 9 days",
    subtitle = "Twitter status (tweet) counts aggregated using three-hour intervals",
    caption = "\nSource: Data collected from Twitter's REST API via rtweet"
  )

library(plotly)
ggplotly(p2)

```


```{r}
tweets_afghanistan_sl12 <- bind_rows(tweets_afghanistan_sl,
                                     tweets_afghanistan_sl2)
## plot time series of tweets
p3 <- ts_plot(tweets_afghanistan_sl12, "3 hours", 
              color = "darkgreen") +
  ggplot2::theme_minimal() +
  ggplot2::theme(plot.title = ggplot2::element_text(face = "bold")) +
  ggplot2::labs(
    x = NULL, y = NULL,
    title = "Frequency of #rollingstones Twitter statuses from past 9 days",
    subtitle = "Twitter status (tweet) counts aggregated using three-hour intervals",
    caption = "\nSource: Data collected from Twitter's REST API via rtweet"
  )

library(plotly)
ggplotly(p3)

```

