---
title: "Slovenska imena"
author: "Teodor Petrič"
date: "19 10 2021"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
```

https://www.stat.si/StatWeb/news/Index/9597

https://pxweb.stat.si/SiStat/sl/Home/GetSearchResultsRedirect?searchQuery=05X1030S%20OR%2005X1005S%20OR%2005X1002S%20OR%2005X1010S%20OR%2005X1015S%20OR%2005X1016S%20OR%2005X1017S%20OR%2005X1018S&searchString=05X1030S%20OR%2005X1005S%20OR%2005X1002S%20OR%2005X1010S%20OR%2005X1015S%20OR%2005X1016S%20OR%2005X1017S%20OR%2005X1018S

https://pxweb.stat.si/SiStatData/pxweb/sl/Data/Data/05X1010S.px/
https://pxweb.stat.si/SiStatData/pxweb/sl/Data/Data/05X1005S.px/

## Podatkovna niza

Glede na majhnost podatkovnih nizov so primerne tudi Excelove datoteke.

```{r}
xlsx_files <- dir("data", pattern = "*.xlsx", full.names = TRUE)
moska_xlsx <- read_xlsx(xlsx_files[1], skip = 3) %>% 
  janitor::clean_names() %>% 
  rename(name = x1) %>% 
  mutate(spol = "moški")
zenska_xlsx <- read_xlsx(xlsx_files[2], skip = 3) %>% 
  janitor::clean_names() %>% 
  rename(name = x1) %>% 
  mutate(spol = "ženski")

slo_imena_xlsx <- bind_rows(moska_xlsx, zenska_xlsx) %>% 
  select(name,spol, x2008:x2021)

slo_imena_xlsx %>% slice_sample(n = 10)
```

Če moramo prebrati številne in velike podatkovne nize so primernejše besedilne datoteke (csv, ...).

```{r}
# Read
files <- dir("data", pattern = "*.csv", full.names = TRUE)
moska <- read.delim(files[1], sep = ",") %>% 
  janitor::clean_names() %>% 
  mutate(spol = "moški")
m1 <- moska %>% 
  select(ime,spol)
m2 <- moska %>% 
  select(-ime, -spol) %>% 
  mutate_all(function(x) gsub("-","0", x)) %>%
  mutate(across(where(is.character), as.numeric))
moska <- bind_cols(m1, m2)

zenska <- read.delim(files[2], sep = ",") %>% 
  janitor::clean_names() %>% 
  mutate(spol = "ženski")
z1 <- zenska %>% 
  select(ime,spol)
z2 <- zenska %>% 
  select(-ime, -spol) %>% 
  mutate_all(function(x) gsub("-","0", x)) %>% 
  mutate(across(where(is.character), as.numeric))
zenska <- bind_cols(z1, z2)

slo_imena <- bind_rows(moska, zenska) %>% 
  select(ime, spol, stevilo_2008:stevilo_2021) %>% 
  rename_all(function(x) gsub("stevilo_", "leto_", x))

slo_imena %>% slice_sample(n = 10)

slo_names <- slo_imena %>% 
  pivot_longer(leto_2008:leto_2021, 
               names_to = c("leto"), values_to = "n") %>% 
  mutate(leto = as.numeric(str_remove(leto, "leto_")))

slo_names %>% slice_sample(n = 10)

```

## Priprava

```{r}
topNames <- slo_names %>%
  filter(leto >= 2008) %>%  
  group_by(ime, spol) %>%
  summarize(n = as.numeric(sum(n))) %>%
  filter(n > 10) %>%
  select(ime, spol)

filteredNames <- slo_names %>%
  filter(leto >= 2008) %>%
  inner_join(topNames)

yearlyNames <- filteredNames %>%
  group_by(leto, ime, spol) %>%
  summarize(n = as.numeric(sum(n)))

```

## Najpopularnejša imena 2008

```{r}
library(scales)
topNames2008 <- yearlyNames %>%
  filter(leto == 2008) %>%
  group_by(ime, spol) %>%
  summarize(n = sum(n)) %>%
  group_by(spol) %>%
  mutate(rank = min_rank(desc(n))) %>%
  filter(rank < 5) %>%
  arrange(spol, rank) %>%
  select(ime, spol, rank)

topNames2008Yearly <- yearlyNames %>%
  inner_join(topNames2008)

ggplot(topNames2008Yearly, aes(leto, n, color = ime)) +
  geom_line() +
  geom_point() +
  # scale_y_log10() +
  facet_grid(~ spol, scales = "free_y") +
  ggtitle("Najpopularnejša imena 2008")
ggsave("pictures/PopNames2008.png")
```


## Najpopularnejša imena 2020

```{r}
topNames2020 <- yearlyNames %>%
  filter(leto == 2020) %>%
  group_by(ime, spol) %>%
  summarize(n = sum(n)) %>%
  group_by(spol) %>%
  mutate(rank = min_rank(desc(n))) %>%
  filter(rank < 5) %>%
  arrange(spol, rank) %>%
  select(ime, spol, rank)

topNames2020Yearly <- yearlyNames %>%
  inner_join(topNames2020)

ggplot(topNames2020Yearly, aes(leto, n, color = ime)) +
  geom_line() +
  geom_point() +
  # scale_y_log10() +
  facet_grid(~ spol, scales = "free_y") +
  ggtitle("Najpopularnejša imena 2020")
ggsave("pictures/PopNames2008.png")
```

## Skupna imena

Katera imena so lahko tako moška kot ženska imena?

```{r}
sharedName <- slo_names %>%
  mutate(male = ifelse(spol == "moški", n, 0), female = ifelse(spol == "ženski", n, 0)) %>%
  group_by(ime) %>%
  summarize(Moski = as.numeric(sum(male)), 
            Zenska = as.numeric(sum(female)),
            n = as.numeric(sum(n)),
            AvgYear = round(as.numeric(sum(leto * n) / sum(n)),0)) %>%
  filter(Moski > 50 & Zenska > 50)
```

```{r}
library(rbokeh)
# or to set the theme for all future plots
options(bokeh_theme = bk_default_theme) # bk_ggplot_theme
figure(width = NULL, height = NULL, 
       xlab = "Število moških", 
       ylab = "Število žensk",
       title = "Skupna imena (2008 - 2020)") %>%
  ly_points(Moski, Zenska, data = sharedName,
            color = AvgYear, size = scale(sqrt(n)),
            hover = list(ime, Moski, Zenska, AvgYear), 
            legend = FALSE) %>%
  ly_abline(0, 1, color = "darkgreen")
```


```{r}
library(ggrepel)
set.seed(43)

shared2 <- sharedName %>% 
  group_by(ime, Moski, Zenska) %>% 
  ggplot(aes(Moski, Zenska, color = AvgYear)) +
  scale_x_log10() +
  scale_y_log10() +
  # geom_point(aes(size = scale(sqrt(n)))) +
  # geom_text(aes(label = ime), check_overlap = T) +
  geom_text_repel(aes(label = ime)) +
  geom_abline(aes(intercept = 0, slope = 1), color = "darkgreen") +
  theme_light() +
  theme(legend.position = "none") +
  labs(x= "Število moških", y = "Število žensk", 
       title = "Skupna imena (2008 - 2020)") 
ggsave("pictures/shared_names2.png")
shared2
```


```{r}
shared <- sharedName %>% 
  group_by(ime, Moski, Zenska) %>% 
  ggplot(aes(Moski, Zenska, color = AvgYear)) +
  # scale_x_continuous(labels = scales::comma_format(accuracy = 1)) +
  scale_x_log10() +
  scale_y_log10() +
  # geom_point(aes(size = scale(sqrt(n)))) +
  geom_text(aes(label = ime), check_overlap = T) +
  geom_abline(aes(intercept = 0, slope = 1), color = "darkgreen") +
  theme_light() +
  theme(legend.position = "none") +
  labs(x= "Število moških", y = "Število žensk", 
       title = "Skupna imena (2008 - 2020)") 
ggsave("pictures/shared_names.png")
shared
```

```{r}
sharedName %>% 
  filter(ime == "Saša")
```

```{r}
library(plotly)
ggplotly(shared, 
  tooltip = c("ime","Moski","Zenska","AvgYear")) %>% 
  layout(legend = list(x = 0.3, y = -0.05, itemsizing = "trace",
                       orientation = "h"))
```


```{r}
library(plotly)
plotly_p1 <- ggplotly(
  shared, width = 850, height = 700, 
  tooltip = c("ime","Moski","Zenska","AvgYear")) %>% 
  layout(dragmode = "pan", 
         legend = list(x = 0.3, y = -0.05, itemsizing = "trace",
                       orientation = "h"))
plotly_p1


##### Save it locally
library(htmlwidgets)
htmlwidgets::saveWidget(as_widget(plotly_p1),
                        "plotly_pics/shared_names.html")
```


```{r}
library(plotly)

x = seq(0, 10^5)
y = seq(0, 10^5)

fig <- sharedName %>% 
  group_by(ime, Moski, Zenska, AvgYear) %>% 
  plot_ly(x = ~Moski, y = ~Zenska, 
          # width = 850, height = 700
          hoveron = c("ime","Moski","Zenska","AvgYear")) %>% 
  # add_markers(text = ~paste("AvgYear: ", AvgYear),
  #             name = "Povprečje/leto",
  #             symbol = I("circle"),
  #             size = I(4),
  #             opacity = I(0.2)) %>% 
  add_markers(text = ~paste("Razmerje M/Ž: ", 
                            round(Moski/Zenska, 2)),
              color = ~Moski/Zenska,
              symbol = I("square"),
              size = I(12),
              opacity = I(1),
              name = "Razmerje M/Ž") %>% 
  add_markers(text = ~paste("Ime: ", ime),
              name = "Osebno ime",
              color = ~Moski/Zenska,
              symbol = I("circle"),
              size = I(1),
              opacity = I(0)) %>%
  layout(
    title = "Število skupnih imen",
    xaxis = list(
      title = "Število moških",
      rangeslider = list(type = "x")
    ),
    yaxis = list(
      title = "Število žensk"
    )
  )
fig  

 ##### Save it locally
library(htmlwidgets)
htmlwidgets::saveWidget(as_widget(fig),
                        "plotly_pics/plotly_fig_shared_names.html")

```



